/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dz.univjijel.ds.controletp01.gui;

import dz.univjijel.ds.controletp01.main.Main;
import dz.univjijel.ds.controletp01.model.Daira;
import dz.univjijel.ds.controletp01.model.Wilaya;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarek Boutefara <t_boutefara@esi.dz>
 */
public class MainFrame extends javax.swing.JFrame {
    
    DefaultTableModel modele = new DefaultTableModel(null, 
            new String[]{"Code Postal", "Nom Daira"});
    int index = -1;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        tblDairas.setModel(modele);
        
        afficherWilaya();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        btnPrecedente = new javax.swing.JButton();
        btnNouvelleW = new javax.swing.JButton();
        btnSuivante = new javax.swing.JButton();
        btnNouvelleD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDairas = new javax.swing.JTable();
        btnFermer = new javax.swing.JButton();
        btnSauver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des Wilaya");
        setResizable(false);

        lblCode.setText("Code :");

        lblNom.setText("Wilaya :");

        txtCode.setEditable(false);

        txtNom.setEditable(false);

        btnPrecedente.setText("Précédente");
        btnPrecedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedenteActionPerformed(evt);
            }
        });

        btnNouvelleW.setText("Nouvelle Wilaya");
        btnNouvelleW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouvelleWActionPerformed(evt);
            }
        });

        btnSuivante.setText("Suivante");
        btnSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivanteActionPerformed(evt);
            }
        });

        btnNouvelleD.setText("Nouvelle Daira");
        btnNouvelleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouvelleDActionPerformed(evt);
            }
        });

        tblDairas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDairas);

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        btnSauver.setText("Sauvegarder");
        btnSauver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNom)
                            .addComponent(lblCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnPrecedente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNouvelleD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNouvelleW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuivante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnSauver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFermer)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrecedente)
                    .addComponent(btnNouvelleW)
                    .addComponent(btnSuivante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNouvelleD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFermer)
                    .addComponent(btnSauver))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnPrecedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedenteActionPerformed
        index--;
        index  = index < 0 ? 0 : index;
        
        afficherWilaya();
    }//GEN-LAST:event_btnPrecedenteActionPerformed

    private void btnSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivanteActionPerformed
        index++;
        index = index >= Main.liste.size() ? Main.liste.size() - 1 : index;
        
        afficherWilaya();
    }//GEN-LAST:event_btnSuivanteActionPerformed

    private void btnNouvelleWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouvelleWActionPerformed
        (new NouvelleWilaya()).setVisible(true);
    }//GEN-LAST:event_btnNouvelleWActionPerformed

    private void btnNouvelleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouvelleDActionPerformed
        (new NouvelleDaira(index)).setVisible(true);
    }//GEN-LAST:event_btnNouvelleDActionPerformed

    private void btnSauverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauverActionPerformed
        Main.sauvegarder();
    }//GEN-LAST:event_btnSauverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnNouvelleD;
    private javax.swing.JButton btnNouvelleW;
    private javax.swing.JButton btnPrecedente;
    private javax.swing.JButton btnSauver;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblNom;
    private javax.swing.JTable tblDairas;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables

    private void afficherWilaya() {
        if(index < Main.liste.size() && index > -1){
            Wilaya w = Main.liste.get(index);
            txtCode.setText(w.getCode() + "");
            txtNom.setText(w.getNom());
            
            modele.setRowCount(0);
            for(Daira d : w.getDairas()){
                modele.addRow(new String[]{d.getCodePostal() + "", d.getNom()});
            }
        }
    }

    void wilayaAjoutee() {
        index = Main.liste.size() - 1;
        
        afficherWilaya();
    }

    void wilayaModifiee() {
        afficherWilaya();
    }
}
